apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
        - name: app
          image: ghcr.io/graylee0128/0717-cicd-demo:ada6c00d7687b9f783be25b644afa46c2a9377c4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
